# Generated by Django 3.1 on 2020-08-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_position', models.CharField(max_length=30)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('referral_id', models.CharField(max_length=15)),
                ('experience_required', models.CharField(default='', max_length=15)),
                ('date_posted', models.DateField()),
                ('job_description', models.TextField()),
                ('job_position', models.ManyToManyField(to='jobs.job')),
            ],
        ),
    ]
