# Generated by Django 3.1 on 2020-08-16 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='job_position',
        ),
        migrations.AddField(
            model_name='post',
            name='job_position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
            preserve_default=False,
        ),
    ]
