# Generated by Django 3.1 on 2020-08-16 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_apply'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='apply',
            new_name='jobApply',
        ),
    ]
