# Generated by Django 3.1 on 2020-08-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20200816_2352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobApply',
            new_name='apply',
        ),
    ]
