# Generated by Django 3.1 on 2020-08-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20200816_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='applied_company',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apply',
            name='applied_position',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apply',
            name='job_referral',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
