# Generated by Django 3.2.13 on 2022-06-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20200824_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='msg_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
